// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vendas.Data.CompiledModels
{
    public partial class DataContextModel
    {
        private DataContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b729736b-dea7-4cf2-aba7-c6e4aab4f0f7"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var itemVenda = ItemVendaEntityType.Create(this);
            var venda = VendaEntityType.Create(this);

            ItemVendaEntityType.CreateForeignKey1(itemVenda, venda);

            ItemVendaEntityType.CreateAnnotations(itemVenda);
            VendaEntityType.CreateAnnotations(venda);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Relational:DefaultSchema", "public");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
