// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Vendas.Data;
using Vendas.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DataContext), typeof(DataContextModel))]
