// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vendas.Core.Entidades;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vendas.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ItemVendaEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vendas.Core.Entidades.ItemVenda",
                typeof(ItemVenda),
                baseEntityType,
                propertyCount: 7,
                complexPropertyCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ItemVenda).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemVenda).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var desconto = runtimeEntityType.AddProperty(
                "Desconto",
                typeof(decimal),
                propertyInfo: typeof(ItemVenda).GetProperty("Desconto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemVenda).GetField("<Desconto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            desconto.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            desconto.AddAnnotation("Relational:ColumnName", "desconto");
            desconto.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var quantidade = runtimeEntityType.AddProperty(
                "Quantidade",
                typeof(decimal),
                propertyInfo: typeof(ItemVenda).GetProperty("Quantidade", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemVenda).GetField("<Quantidade>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            quantidade.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            quantidade.AddAnnotation("Relational:ColumnName", "quantidade");
            quantidade.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var valorTotal = runtimeEntityType.AddProperty(
                "ValorTotal",
                typeof(decimal),
                propertyInfo: typeof(ItemVenda).GetProperty("ValorTotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemVenda).GetField("<ValorTotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            valorTotal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            valorTotal.AddAnnotation("Relational:ColumnName", "valor_total");
            valorTotal.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var valorTotalSemDesconto = runtimeEntityType.AddProperty(
                "ValorTotalSemDesconto",
                typeof(decimal),
                propertyInfo: typeof(ItemVenda).GetProperty("ValorTotalSemDesconto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemVenda).GetField("<ValorTotalSemDesconto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            valorTotalSemDesconto.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            valorTotalSemDesconto.AddAnnotation("Relational:ColumnName", "valor_total_sem_desconto");
            valorTotalSemDesconto.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var valorUnitario = runtimeEntityType.AddProperty(
                "ValorUnitario",
                typeof(decimal),
                propertyInfo: typeof(ItemVenda).GetProperty("ValorUnitario", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ItemVenda).GetField("<ValorUnitario>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            valorUnitario.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            valorUnitario.AddAnnotation("Relational:ColumnName", "valor_unitario");
            valorUnitario.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var vendaId = runtimeEntityType.AddProperty(
                "VendaId",
                typeof(Guid),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            vendaId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            vendaId.AddAnnotation("Relational:ColumnName", "venda_id");

            ProdutoComplexProperty.Create(runtimeEntityType);
            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_items_venda");

            var index = runtimeEntityType.AddIndex(
                new[] { vendaId });
            index.AddAnnotation("Relational:Name", "ix_items_venda_venda_id");

            return runtimeEntityType;
        }

        public static class ProdutoComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("Produto",
                    typeof(Produto),
                    "Vendas.Core.Entidades.ItemVenda.Produto#Produto",
                    typeof(Produto),
                    propertyInfo: typeof(ItemVenda).GetProperty("Produto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(ItemVenda).GetField("<Produto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    propertyCount: 5);

                var complexType = complexProperty.ComplexType;
                var codigo = complexType.AddProperty(
                    "Codigo",
                    typeof(string),
                    propertyInfo: typeof(Produto).GetProperty("Codigo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Produto).GetField("<Codigo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                codigo.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                codigo.AddAnnotation("Relational:ColumnName", "produto_codigo");
                codigo.AddAnnotation("Relational:ColumnType", "varchar");

                var descricao = complexType.AddProperty(
                    "Descricao",
                    typeof(string),
                    propertyInfo: typeof(Produto).GetProperty("Descricao", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Produto).GetField("<Descricao>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                descricao.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                descricao.AddAnnotation("Relational:ColumnName", "produto_descricao");
                descricao.AddAnnotation("Relational:ColumnType", "varchar");

                var ean = complexType.AddProperty(
                    "Ean",
                    typeof(string),
                    propertyInfo: typeof(Produto).GetProperty("Ean", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Produto).GetField("<Ean>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                ean.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                ean.AddAnnotation("Relational:ColumnName", "produto_ean");
                ean.AddAnnotation("Relational:ColumnType", "varchar");

                var idExterno = complexType.AddProperty(
                    "IdExterno",
                    typeof(Guid),
                    propertyInfo: typeof(Produto).GetProperty("IdExterno", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Produto).GetField("<IdExterno>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
                idExterno.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                idExterno.AddAnnotation("Relational:ColumnName", "produto_id_externo");

                var nome = complexType.AddProperty(
                    "Nome",
                    typeof(string),
                    propertyInfo: typeof(Produto).GetProperty("Nome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Produto).GetField("<Nome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                nome.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                nome.AddAnnotation("Relational:ColumnName", "produto_nome");
                nome.AddAnnotation("Relational:ColumnType", "varchar");

                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", "public");
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "items_venda");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("VendaId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var itens = principalEntityType.AddNavigation("Itens",
                runtimeForeignKey,
                onDependent: false,
                typeof(IReadOnlyList<ItemVenda>),
                propertyInfo: typeof(Venda).GetProperty("Itens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("_itens", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "fk_items_venda_vendas_venda_id");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "public");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "items_venda");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
