// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vendas.Core.Entidades;
using Vendas.Core.ValueObjects;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Vendas.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class VendaEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Vendas.Core.Entidades.Venda",
                typeof(Venda),
                baseEntityType,
                propertyCount: 10,
                complexPropertyCount: 2,
                navigationCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Venda).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            id.AddAnnotation("Relational:ColumnName", "id");

            var alteradaEm = runtimeEntityType.AddProperty(
                "AlteradaEm",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(Venda).GetProperty("AlteradaEm", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<AlteradaEm>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            alteradaEm.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            alteradaEm.AddAnnotation("Relational:ColumnName", "alterada_em");

            var criadaEm = runtimeEntityType.AddProperty(
                "CriadaEm",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Venda).GetProperty("CriadaEm", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<CriadaEm>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            criadaEm.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            criadaEm.AddAnnotation("Relational:ColumnName", "criada_em");

            var data = runtimeEntityType.AddProperty(
                "Data",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Venda).GetProperty("Data", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<Data>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            data.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            data.AddAnnotation("Relational:ColumnName", "data");

            var desconto = runtimeEntityType.AddProperty(
                "Desconto",
                typeof(decimal),
                propertyInfo: typeof(Venda).GetProperty("Desconto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<Desconto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            desconto.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            desconto.AddAnnotation("Relational:ColumnName", "desconto");
            desconto.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var idExterno = runtimeEntityType.AddProperty(
                "IdExterno",
                typeof(Guid),
                propertyInfo: typeof(Venda).GetProperty("IdExterno", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<IdExterno>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            idExterno.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            idExterno.AddAnnotation("Relational:ColumnName", "id_externo");

            var numero = runtimeEntityType.AddProperty(
                "Numero",
                typeof(string),
                propertyInfo: typeof(Venda).GetProperty("Numero", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<Numero>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            numero.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            numero.AddAnnotation("Relational:ColumnName", "numero");
            numero.AddAnnotation("Relational:ColumnType", "varchar");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(StatusVenda),
                propertyInfo: typeof(Venda).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: StatusVenda.Criada);
            status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            status.AddAnnotation("Relational:ColumnName", "status");

            var valorTotal = runtimeEntityType.AddProperty(
                "ValorTotal",
                typeof(decimal),
                propertyInfo: typeof(Venda).GetProperty("ValorTotal", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<ValorTotal>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            valorTotal.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            valorTotal.AddAnnotation("Relational:ColumnName", "valor_total");
            valorTotal.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            var valorTotalSemDesconto = runtimeEntityType.AddProperty(
                "ValorTotalSemDesconto",
                typeof(decimal),
                propertyInfo: typeof(Venda).GetProperty("ValorTotalSemDesconto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Venda).GetField("<ValorTotalSemDesconto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            valorTotalSemDesconto.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
            valorTotalSemDesconto.AddAnnotation("Relational:ColumnName", "valor_total_sem_desconto");
            valorTotalSemDesconto.AddAnnotation("Relational:ColumnType", "numeric(14,2)");

            ClienteComplexProperty.Create(runtimeEntityType);
            FilialComplexProperty.Create(runtimeEntityType);
            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "pk_vendas");

            var index = runtimeEntityType.AddIndex(
                new[] { criadaEm });
            index.AddAnnotation("Relational:Name", "ix_vendas_criada_em");

            return runtimeEntityType;
        }

        public static class ClienteComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("Cliente",
                    typeof(Cliente),
                    "Vendas.Core.Entidades.Venda.Cliente#Cliente",
                    typeof(Cliente),
                    propertyInfo: typeof(Venda).GetProperty("Cliente", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Venda).GetField("<Cliente>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    propertyCount: 2,
                    complexPropertyCount: 1);

                var complexType = complexProperty.ComplexType;
                var idExterno = complexType.AddProperty(
                    "IdExterno",
                    typeof(Guid),
                    propertyInfo: typeof(Cliente).GetProperty("IdExterno", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Cliente).GetField("<IdExterno>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
                idExterno.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                idExterno.AddAnnotation("Relational:ColumnName", "cliente_id_externo");

                var nome = complexType.AddProperty(
                    "Nome",
                    typeof(string),
                    propertyInfo: typeof(Cliente).GetProperty("Nome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Cliente).GetField("<Nome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                nome.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                nome.AddAnnotation("Relational:ColumnName", "cliente_nome");
                nome.AddAnnotation("Relational:ColumnType", "varchar");

                CnpjComplexProperty.Create(complexType);
                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", "public");
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "vendas");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }

            public static class CnpjComplexProperty
            {
                public static RuntimeComplexProperty Create(RuntimeComplexType declaringType)
                {
                    var complexProperty = declaringType.AddComplexProperty("Cnpj",
                        typeof(Cnpj),
                        "Vendas.Core.Entidades.Venda.Cliente#Cliente.Cnpj#Cnpj",
                        typeof(Cnpj),
                        propertyInfo: typeof(Cliente).GetProperty("Cnpj", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                        fieldInfo: typeof(Cliente).GetField("<Cnpj>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                        propertyCount: 1);

                    var complexType = complexProperty.ComplexType;
                    var numero = complexType.AddProperty(
                        "Numero",
                        typeof(string),
                        propertyInfo: typeof(Cnpj).GetProperty("Numero", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                        fieldInfo: typeof(Cnpj).GetField("<Numero>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                    numero.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                    numero.AddAnnotation("Relational:ColumnName", "cliente_cnpj_numero");
                    numero.AddAnnotation("Relational:ColumnType", "varchar(14)");

                    complexType.AddAnnotation("Relational:FunctionName", null);
                    complexType.AddAnnotation("Relational:Schema", "public");
                    complexType.AddAnnotation("Relational:SqlQuery", null);
                    complexType.AddAnnotation("Relational:TableName", "vendas");
                    complexType.AddAnnotation("Relational:ViewName", null);
                    complexType.AddAnnotation("Relational:ViewSchema", null);
                    return complexProperty;
                }
            }
        }

        public static class FilialComplexProperty
        {
            public static RuntimeComplexProperty Create(RuntimeEntityType declaringType)
            {
                var complexProperty = declaringType.AddComplexProperty("Filial",
                    typeof(Filial),
                    "Vendas.Core.Entidades.Venda.Filial#Filial",
                    typeof(Filial),
                    propertyInfo: typeof(Venda).GetProperty("Filial", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Venda).GetField("<Filial>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    propertyCount: 3);

                var complexType = complexProperty.ComplexType;
                var idExterno = complexType.AddProperty(
                    "IdExterno",
                    typeof(Guid),
                    propertyInfo: typeof(Filial).GetProperty("IdExterno", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Filial).GetField("<IdExterno>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
                idExterno.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                idExterno.AddAnnotation("Relational:ColumnName", "filial_id_externo");

                var nome = complexType.AddProperty(
                    "Nome",
                    typeof(string),
                    propertyInfo: typeof(Filial).GetProperty("Nome", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Filial).GetField("<Nome>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                nome.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                nome.AddAnnotation("Relational:ColumnName", "filial_nome");
                nome.AddAnnotation("Relational:ColumnType", "varchar");

                var numero = complexType.AddProperty(
                    "Numero",
                    typeof(string),
                    propertyInfo: typeof(Filial).GetProperty("Numero", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                    fieldInfo: typeof(Filial).GetField("<Numero>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
                numero.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);
                numero.AddAnnotation("Relational:ColumnName", "filial_numero");
                numero.AddAnnotation("Relational:ColumnType", "varchar");

                complexType.AddAnnotation("Relational:FunctionName", null);
                complexType.AddAnnotation("Relational:Schema", "public");
                complexType.AddAnnotation("Relational:SqlQuery", null);
                complexType.AddAnnotation("Relational:TableName", "vendas");
                complexType.AddAnnotation("Relational:ViewName", null);
                complexType.AddAnnotation("Relational:ViewSchema", null);
                return complexProperty;
            }
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "public");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "vendas");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
