// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vendas.Core.Entidades;
using Vendas.Data;

#nullable disable

namespace Vendas.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_venda", new[] { "cancelada", "criada" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vendas.Core.Entidades.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desconto");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorTotalSemDesconto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_total_sem_desconto");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_unitario");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.ComplexProperty<Dictionary<string, object>>("Produto", "Vendas.Core.Entidades.ItemVenda.Produto#Produto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("produto_codigo");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("produto_descricao");

                            b1.Property<string>("Ean")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("produto_ean");

                            b1.Property<Guid>("IdExterno")
                                .HasColumnType("uuid")
                                .HasColumnName("produto_id_externo");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("produto_nome");
                        });

                    b.HasKey("Id")
                        .HasName("pk_items_venda");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_items_venda_venda_id");

                    b.ToTable("items_venda", "public");
                });

            modelBuilder.Entity("Vendas.Core.Entidades.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AlteradaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterada_em");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desconto");

                    b.Property<Guid>("IdExterno")
                        .HasColumnType("uuid")
                        .HasColumnName("id_externo");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("numero");

                    b.Property<StatusVenda>("Status")
                        .HasColumnType("status_venda")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorTotalSemDesconto")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_total_sem_desconto");

                    b.ComplexProperty<Dictionary<string, object>>("Cliente", "Vendas.Core.Entidades.Venda.Cliente#Cliente", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("IdExterno")
                                .HasColumnType("uuid")
                                .HasColumnName("cliente_id_externo");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("cliente_nome");

                            b1.ComplexProperty<Dictionary<string, object>>("Cnpj", "Vendas.Core.Entidades.Venda.Cliente#Cliente.Cnpj#Cnpj", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasColumnType("varchar(14)")
                                        .HasColumnName("cliente_cnpj_numero");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Filial", "Vendas.Core.Entidades.Venda.Filial#Filial", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("IdExterno")
                                .HasColumnType("uuid")
                                .HasColumnName("filial_id_externo");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("filial_nome");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar")
                                .HasColumnName("filial_numero");
                        });

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("CriadaEm")
                        .HasDatabaseName("ix_vendas_criada_em");

                    b.ToTable("vendas", "public");
                });

            modelBuilder.Entity("Vendas.Core.Entidades.ItemVenda", b =>
                {
                    b.HasOne("Vendas.Core.Entidades.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_venda_vendas_venda_id");
                });

            modelBuilder.Entity("Vendas.Core.Entidades.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
